#!/usr/bin/env python3

from ev3dev2.motor import LargeMotor, OUTPUT_A, OUTPUT_B
from ev3dev2.sensor.lego import ColorSensor
from ev3dev2.sensor import INPUT_1
from time import sleep

left = LargeMotor(OUTPUT_A)
right = LargeMotor(OUTPUT_B)

color = ColorSensor(INPUT_1)

target = 50
tolerance = 3
speed = 180

while True:

    light = color.reflected_light_intensity
    error = light - target

    if abs(error) <= tolerance:
      
        left.run_forever(speed_sp=speed)
        right.run_forever(speed_sp=speed)

    elif error > 0:
     
        left.run_forever(speed_sp=speed)
        right.run_forever(speed_sp=-80)  
    else:
  
        left.run_forever(speed_sp=-80)
        right.run_forever(speed_sp=speed)

    sleep(0.01)
